// Code generated by scripts/generate-crawl-jobs-v2-bundle.py; DO NOT EDIT.
// Complete source identity only; NOT commit-guard approval or runtime activation.
package crawljobsv2

import "embed"

// all: includes hidden files and subdirectories so validation cannot silently omit them.
//
//go:embed all:lua
var authoritativeLuaFS embed.FS

const canonicalSourceSetSHA256 Digest = "10a4f753395a6d1bccc587194ef2af6346ca3c03f8a8faf71081abc800ac13b8"
const canonicalContractSHA256 Digest = "df171381f4f1bb6d8daec60b9173254f8ae77cfc24907d0a69b279cab89fa562"
const canonicalBundleSealSHA256 Digest = "7ec16509119c44a02eafa8c342fe777dfa6b769937c1681efbabb2fc36823614"

// A fresh literal array, never a mutable package-level manifest.
func canonicalScriptBindingPins() [43]scriptBinding {
	return [43]scriptBinding{
		{operation: "CJ2_APPROVE_BOOT", sourceName: "cj2_approve_boot.lua", redisSHA1: "04c7743f73baf9a1ec452b9f3dbefe2ad96c2039", sourceSHA256: "5582ad554f4bdf5b44ef5f0cae3abe51b5e4c7bb9d350c8647d0ceb356415fe5"},
		{operation: "CJ2_INSTALL_CANDIDATE_MARKERS", sourceName: "cj2_install_candidate_markers.lua", redisSHA1: "5fdbf9707c070ef7dc190e63bd1f7b6979d417e5", sourceSHA256: "c2fee1de9e8d32af700f12bce5c5db464f61facb353c77b823038b3283511411"},
		{operation: "CJ2_RETIRE_LEGACY_KEYS", sourceName: "cj2_retire_legacy_keys.lua", redisSHA1: "309ed223afad732ce9d392413274fbb66aa4564a", sourceSHA256: "702b096b843d80cd1c85186cf79fafa29c08766ea22c599af29877e1e8013fc7"},
		{operation: "CJ2_PROMOTE_CANDIDATE_CONTRACTS", sourceName: "cj2_promote_candidate_contracts.lua", redisSHA1: "4d9e4a717129a6bd4c92c06544b249faa1463f69", sourceSHA256: "cb7ccb47dacb17058a20fdf0990242e79c486999df5dacd4677f21c4be00ca92"},
		{operation: "CJ2_MARK_PLANNED_SHUTDOWN", sourceName: "cj2_mark_planned_shutdown.lua", redisSHA1: "aff3cd297f014a7d9545be3b6c5e3fee69d362fe", sourceSHA256: "a401163390a105babd6ee8849c3b5e4ee490c1b6df7420b3b497d6c2891fc6ba"},
		{operation: "CJ2_CREATE_RUN", sourceName: "cj2_create_run.lua", redisSHA1: "e9e60605a05bc6d683d9e6a1fec0d617c5add8d7", sourceSHA256: "b308e4764f976606daa8e62b2c0fce8641918786745c58fe47763f64434e821c"},
		{operation: "CJ2_ENQUEUE_BATCH", sourceName: "cj2_enqueue_batch.lua", redisSHA1: "b7685a05d699937fee277cdec6cb96e72b148437", sourceSHA256: "930363503c0c1660b2364b853e420df4d99998a64c0a434e8c7b5fc579783e26"},
		{operation: "CJ2_BEGIN_RUN_AUDIT", sourceName: "cj2_begin_run_audit.lua", redisSHA1: "c224116bd582d673a9350e6b623b05a3955b3a4a", sourceSHA256: "7d54a589e01ea473b1469f525226ec8686d54e27463e3d9892c7d141f58cb3b6"},
		{operation: "CJ2_AUDIT_RUN_BATCH", sourceName: "cj2_audit_run_batch.lua", redisSHA1: "3869e3b061daf642d0729c63001769ac9a4b8b76", sourceSHA256: "7ef8d831162c583c186b0b58cc17ed6385a9e9fd6f3213462f8b2d902db44de7"},
		{operation: "CJ2_SEAL_RUN", sourceName: "cj2_seal_run.lua", redisSHA1: "8da35fe1518240e262caca7cba47c92133e0108c", sourceSHA256: "c476472c7434f0a727cad414f0ef2178c83bd2b4519bccb9081a2bf41c35c4dc"},
		{operation: "CJ2_ACTIVATE_RUN", sourceName: "cj2_activate_run.lua", redisSHA1: "0b40a591cfe639eb3b63f8537ad5fced8562e81c", sourceSHA256: "583572eab3fa4959dd3a6aaa632a533ada57d5eca30f5e5bb17958667f37459e"},
		{operation: "CJ2_REJECT_READY", sourceName: "cj2_reject_ready.lua", redisSHA1: "bfa4d98e34bb383240e4387fa8c9bb5fcb665c5c", sourceSHA256: "774d34fff36e62356d94cfea2128d7677da8c8089c845f1c2da213d88943efe3"},
		{operation: "CJ2_TRY_CLAIM", sourceName: "cj2_try_claim.lua", redisSHA1: "c13609c959677edd6ab2cdbd525b77689a6a05de", sourceSHA256: "6587f88b1476081881c46fec23867b75294f34568e62aa93ecda6b8b63ed8fec"},
		{operation: "CJ2_RENEW_LEASE", sourceName: "cj2_renew_lease.lua", redisSHA1: "9b1facfd8083e0be9b37313a21074d438d42d108", sourceSHA256: "8ca4926d7f5d5a230a31c21fad0c21bc67f4f303e417c23da926915e5079d4d4"},
		{operation: "CJ2_RESERVE_REQUEST", sourceName: "cj2_reserve_request.lua", redisSHA1: "1dca96666af1193d71164b839963e9af50f5b0df", sourceSHA256: "f6017525fad5bd874f0a01830f418c9b216c769cb698127e5cad01fe6d4c9543"},
		{operation: "CJ2_START_REQUEST", sourceName: "cj2_start_request.lua", redisSHA1: "ecc128a287a90d41c96ae336af86d281c0f9591d", sourceSHA256: "4294f96880cf92970855c2848a2852ddf4bd2052eeb3573c24e2d35aa8d7dbb9"},
		{operation: "CJ2_FINISH_REQUEST", sourceName: "cj2_finish_request.lua", redisSHA1: "97be2772a35cc6a79b09d136590175460823319d", sourceSHA256: "98ed75748901dc0059383e3a25101bceca43d7cf24f2e992f1821f5ba2ca5691"},
		{operation: "CJ2_CANCEL_RESERVATION", sourceName: "cj2_cancel_reservation.lua", redisSHA1: "3830bbd5bf0e5e21924fda4ec44ea3253bbaa022", sourceSHA256: "b049f917a347414d85e2372be4867db35f7a9ee7a986e58935406d9182c019bf"},
		{operation: "CJ2_RELEASE_BEFORE_IO", sourceName: "cj2_release_before_io.lua", redisSHA1: "8cc301d978e11715a8ef52baf368b015621cc25f", sourceSHA256: "517994522df0ec61755af83d6582cff6e7e822c1aaae4f0add6fa0fdaf6b5273"},
		{operation: "CJ2_RETRY", sourceName: "cj2_retry.lua", redisSHA1: "24e772c155d631a1c4f9ade6e692c315322889d2", sourceSHA256: "26917f76deb5cbedc5843950765544ba4eccd45e19049bf9b26b42ff208f133d"},
		{operation: "CJ2_DEAD", sourceName: "cj2_dead.lua", redisSHA1: "5ccd60de489ff0a9609f015135ce73f4640f6196", sourceSHA256: "72680cbf674adf7d9ad894b7d4f6f4545d68bb7b7dfccbc40540e66bb9e89f5d"},
		{operation: "CJ2_CANCEL_JOB", sourceName: "cj2_cancel_job.lua", redisSHA1: "85b1ac8528326b1cea9994dfd6ee34475beeb1bf", sourceSHA256: "0b0845aca099afff71883b6047f8e241da17c8eadc683a9805500785a45b1561"},
		{operation: "CJ2_COMPLETE_NO_OUTPUT", sourceName: "cj2_complete_no_output.lua", redisSHA1: "ce0335a4491aa872001b35152a7f139f72f4af42", sourceSHA256: "bdc0d74578a399c2f3361342cfe14333aa7d94e84487e6b0ec2d3e3981af2aa0"},
		{operation: "CJ2_BEGIN_STAGE", sourceName: "cj2_begin_stage.lua", redisSHA1: "10b8ec42c3c31893b2797fceb8b1dfea12225e22", sourceSHA256: "9b132c580ba07473ebceb1e26927048f864e07867d4e2a1eb05aa007af058742"},
		{operation: "CJ2_STAGE_PAGE_FIELDS", sourceName: "cj2_stage_page_fields.lua", redisSHA1: "eb3b1fb6ded76c82fa9e93fe20940d2bb0ba0c8c", sourceSHA256: "ece694ad9ae49c6a3021efe8cfd6fcbc2cc80e1536cd5e24407d5480f06d0b2a"},
		{operation: "CJ2_STAGE_PAGE_BLOB", sourceName: "cj2_stage_page_blob.lua", redisSHA1: "d6d49d263b781f250053da61a2b5f8bd2edc5cce", sourceSHA256: "374a28965da8b1568dfb37f0a6d3850ea7e8b55367c1e016fb7f7d8144b0e6eb"},
		{operation: "CJ2_STAGE_OUTLINKS_BATCH", sourceName: "cj2_stage_outlinks_batch.lua", redisSHA1: "f78e2cde3bc928227afb3ba17b0d3e1c7af31697", sourceSHA256: "975cab8b6070826266fd72417176c7848ed5da989901f2be9c254dcb8280ab0b"},
		{operation: "CJ2_STAGE_DISCOVERIES_BATCH", sourceName: "cj2_stage_discoveries_batch.lua", redisSHA1: "7d6aa5fc65a0cfb33b960bed3769474a3ec4e4db", sourceSHA256: "e4dfd0e8f3984f1b3805b1fd258903a459214a479d55212ac7b202930074b775"},
		{operation: "CJ2_STAGE_ALIASES_BATCH", sourceName: "cj2_stage_aliases_batch.lua", redisSHA1: "cd801b0679f4a63e478746217d49eb5a9aacb4ad", sourceSHA256: "6fd81bc324c9fcc169f29420e9556675445c13b9c421c9cf0a4a7f5596669803"},
		{operation: "CJ2_STAGE_IMAGES_BATCH", sourceName: "cj2_stage_images_batch.lua", redisSHA1: "3aa873b5186af789dbf9aa412b79b934a708abae", sourceSHA256: "5e53cf203dec5257c5560f340c8503a808cbf42a335400d3897cb629bc5d01dc"},
		{operation: "CJ2_STAGE_IMAGE_MANIFEST", sourceName: "cj2_stage_image_manifest.lua", redisSHA1: "d40904231bde7483f2320200c87ed9f569ce6f01", sourceSHA256: "5aae49beb6e3ec8802ecc6910558b09f6466df36596a06e68f51116766cef717"},
		{operation: "CJ2_ABORT_STAGE", sourceName: "cj2_abort_stage.lua", redisSHA1: "f4b8960613fd477123b6e88a338dcf3f2001f773", sourceSHA256: "c0641701c14c4ae64bb06bad866294de07e3673dd0ea8253342c1734936981fa"},
		{operation: "CJ2_SEAL_STAGE", sourceName: "cj2_seal_stage.lua", redisSHA1: "95c340946456554439a5d288d62b0647d77a1db8", sourceSHA256: "8882be472642b0f939e13300d38230136135cf8e2f525d809bcc24ab9463b5d3"},
		{operation: "CJ2_COMMIT", sourceName: "cj2_commit.lua", redisSHA1: "d187ed1bda07f50f6e15ffc7fa5e515bf3bfe9fa", sourceSHA256: "e6d9f14ccc566cff43148790af96f1b2d65e890a2a4e7b33e3bb475c1427d4fe"},
		{operation: "CJ2_PROMOTE_DUE", sourceName: "cj2_promote_due.lua", redisSHA1: "427c7f36b8102895d3075faccc34a0aa84d4bff7", sourceSHA256: "9db6477d5388ce8644441bd7e82ee43cca087cd70ea3a2f364ce90a1a8602804"},
		{operation: "CJ2_RECOVER_EXPIRED", sourceName: "cj2_recover_expired.lua", redisSHA1: "0f1e80f9f1aa00dc49661c8f09b25fb6277b6b32", sourceSHA256: "430c7b9d3b5cfe734652755ad74e431312cfae619aef517a7ae2dc1e9c21954a"},
		{operation: "CJ2_CANCEL_RUN", sourceName: "cj2_cancel_run.lua", redisSHA1: "cecdc680f14b2ada001b3fc147707bd636a000f6", sourceSHA256: "12f89cab604085c521d141b66d1be323a1adaa299884d489987f02243859404d"},
		{operation: "CJ2_CANCEL_BATCH", sourceName: "cj2_cancel_batch.lua", redisSHA1: "e129b2a8c4a688e9a9325ee08513462a49e6d978", sourceSHA256: "06700f9fd2f6ac228d95970e629ef034e51cd8eec67a0fd4b8711fd17fb485f7"},
		{operation: "CJ2_FINALIZE_RUN", sourceName: "cj2_finalize_run.lua", redisSHA1: "7cfba8086843a2239253cf61d628fec372bdcca5", sourceSHA256: "a273a60dd1d097915f9e61a941a43295279c7c15dbc418393f9a22fc2b7fc83b"},
		{operation: "CJ2_ARCHIVE_RUN", sourceName: "cj2_archive_run.lua", redisSHA1: "270e24f013f439af2d38881eaaf4ce19a30c510f", sourceSHA256: "2a9b0bc0ba976a376b15fdc9ee0fd434195427a2721d8d2efbf8360160d47cef"},
		{operation: "CJ2_PURGE_RUN_BATCH", sourceName: "cj2_purge_run_batch.lua", redisSHA1: "b73621f80a7add66a6bf75521e6c2a60f1b8c725", sourceSHA256: "4040f9c1ef2499ed8fa707a56bd65c8b044440bc7b258079d80231bdc217d149"},
		{operation: "CJ2_CLEAN_STAGE", sourceName: "cj2_clean_stage.lua", redisSHA1: "d9be1295c592389f32e51a2883c6feec31e7c8b1", sourceSHA256: "220ff429516340604adc3914004b0a207bde491faf7d4d50342fdc525313345e"},
		{operation: "CJ2_MAINTAIN_RATE_SCOPES", sourceName: "cj2_maintain_rate_scopes.lua", redisSHA1: "00ce3177597cb98138292d88631da13856722c9c", sourceSHA256: "97aec3d6bf98d422fe3f890064ad387eefeb34e0575ce85323e7e057d711c8bf"},
	}
}
