IMAGE_INDEXER_QUEUE_KEY = "image_indexer_queue"
IMAGE_PROCESSING_QUEUE_KEY = "image_indexer_queue:processing"
IMAGE_DEAD_LETTER_QUEUE_KEY = "image_indexer_queue:dead"
IMAGE_OWNER_LOCK_KEY = "image_indexer_queue:owner"
IMAGE_FENCE_EPOCH_KEY = "image_indexer_queue:fence_epoch"

IMAGE_LOCK_TTL_SECONDS = 60
IMAGE_LOCK_RENEW_SECONDS = 10
IMAGE_RECOVERY_BATCH_SIZE = 100
IMAGE_CLAIM_POLL_SECONDS = 0.1
IMAGE_DEAD_LETTER_MAX_ENTRIES = 1000

PAGE_IMAGES_PREFIX = "page_images"
IMAGE_PREFIX = "image_data"
MAX_CANONICAL_URL_BYTES = 2048
MAX_IMAGE_ALT_BYTES = 4096
MAX_IMAGES_PER_PAGE = 1000
MAX_MANIFEST_BYTES = 4 * 1024 * 1024
MAX_INDEX_WORDS = 1000

FILE_TYPES = {"png", "svg", "ico", "gif", "jpeg", "jpg"}
