# Generated by ../tools/vendor_nlp.py; private build data ONLY, never checked into Git.
# nltk_data commit 550b6625bcef1f2abff2ff770a5a0d272c9c6b2a. SHA-256 is over exact unmodified bytes.
ASSETS = {
    "data/english_stopwords.txt": {
        "bytes": 1048,
        "rows": 198,
        "sha256": "f6d005956f407dbc6ea32e5ff0c7e8e6f71488d3239b9023efdc7fc139d6375b"
    },
    "data/punkt_tab/english/abbrev_types.txt": {
        "bytes": 619,
        "rows": 156,
        "sha256": "92a3e070f43d9b4c5534758ca40ad7343b04e7e29bfe0c2eb658a39445a4f779"
    },
    "data/punkt_tab/english/collocations.tab": {
        "bytes": 594,
        "rows": 37,
        "sha256": "8e2da1225e4dd2cc9dba261ee231ccb134859e21b46006e7f472c5ee269af0cf"
    },
    "data/punkt_tab/english/ortho_context.tab": {
        "bytes": 236303,
        "rows": 20366,
        "sha256": "4bbcca25ed3d3f06c02402abf8419b9f033b8adc06e7b482eca4e45f81a5dc4c"
    },
    "data/punkt_tab/english/sent_starters.txt": {
        "bytes": 241,
        "rows": 39,
        "sha256": "f3f8535483e1dba487241b764945168123bca3209a9645e59acd1225dc76edac"
    }
}
