"""Independent, offline Python validation of canonical URL V1 identities.

Authority: Go 1.25.13, x/net v0.58.0, x/text v0.41.0, Unicode 15.0.0.
Only immutable property bytes are shared with Lua. No Lua, Go, subprocess,
network, Python IDNA codec, or host unicodedata implementation is executed here.
The checked-in data is loaded from ONE fixed path relative to this helper, never
from a fixture, current directory, environment variable, or search path.

Identity is NOT crawl admission. validate_identity permits IP/local/non-default
port identities; derive_origin additionally rejects IPs. Policy, transcript and
source/discovery binding callers must explicitly derive_origin. Structural
output/chunk codecs and URL-ID hashes use validate_identity. Neither operation
authorizes a network request or replaces static/dynamic crawl policy.

The NFC and IDNA algorithms preserve the pinned Go implementation details, not
an idealized replacement standard: byte-indexed hyphens, no ContextO, conditional
per-label bidi, ContextJ zero-default transitions, stream-safe normalization,
and the uint16-truncated composition keys. Adapted from the Go Authors' 2011
and 2016 sources; BSD-3-Clause/PATENTS and Unicode notices are retained beside
the data in services/spider/internal/database/crawljobsv2/lua_src/licenses/.
"""

# Portions Copyright 2011 The Go Authors. All rights reserved.
# Portions Copyright 2016 The Go Authors. All rights reserved.

from __future__ import annotations

import hashlib
import re
import struct
from bisect import bisect_right
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import NamedTuple


DATA_IDENTITY = "cj2-url-v1/go1.25.13/x-net-v0.58.0/x-text-v0.41.0/unicode-15.0.0/data-1"
DATA_SHA256 = "07243776f0a5b1691e872cf92bddaf60cebf292175f25e2146a65220f20e849e"
DATA_SOURCE_BYTES = 273_023
GO_PROPERTY_ORACLE_SHA256 = "b728aa7ae09b7e577fead2845d3489daf7e20d427b2a23ef0ffcd7b1722d5981"
DATA_PATH = (
    Path(__file__).resolve().parents[1]
    / "services/spider/internal/database/crawljobsv2/lua_src/unicode_data.lua"
)
PACKED_SIZES = MappingProxyType({
    "ranges": 6_461 * 5, "props": 2_099 * 9, "decomp": 9_804,
    "compositions": 941 * 7, "ascii": 128 * 2,
})
_PREFIX = (
    b"-- Generated by tools/generate-unicode; DO NOT EDIT.\n"
    b"-- Go Authors BSD-3-Clause; Unicode notices: licenses/.\n"
    b"-- Exact source provenance: unicode-provenance.json. No runtime loaders.\n"
    b"local byte, floor = string.byte, math.floor\n"
)
_LITERAL = re.compile(rb'    "((?:\\[0-9]{3})+)"( \.\.)?\n')


class TableDataError(RuntimeError):
    """Missing/changed/invalid reviewed data: a verifier failure, never fallback."""


class URLValidationError(ValueError):
    """Closed fixture rejection code; no URL or decoded label in diagnostics."""

    def __init__(self, code: str = "CANONICAL_URL_NOT_CANONICAL"):
        super().__init__(code)
        self.code = code


def _uint(data: bytes, offset: int, size: int) -> int:
    return int.from_bytes(data[offset:offset + size], "big")


def parse_pinned_literals(source: bytes) -> MappingProxyType:
    """Accept ONLY the pinned file and its five ordered decimal-escape literals.

    The full-file hash also authenticates the unparsed Lua function trailer. It
    is never evaluated. This is not a general Lua parser and has no executable
    expression, escape, duplicate-field, or unknown-artifact fallback.
    """
    if type(source) is not bytes or len(source) != DATA_SOURCE_BYTES:
        raise TableDataError("Unicode source length mismatch")
    if hashlib.sha256(source).hexdigest() != DATA_SHA256:
        raise TableDataError("Unicode source hash mismatch")
    if not source.startswith(_PREFIX):
        raise TableDataError("Unicode source header mismatch")
    position = len(_PREFIX)
    packed = {}
    for name, size in PACKED_SIZES.items():
        declaration = b"local " + name.encode("ascii") + b" =\n"
        if source[position:position + len(declaration)] != declaration:
            raise TableDataError("Unicode literal inventory/order mismatch")
        position += len(declaration)
        chunks = []
        while True:
            match = _LITERAL.match(source, position)
            if match is None:
                raise TableDataError("Unicode literal grammar mismatch")
            escaped, continuation = match.groups()
            try:
                chunk = bytes(int(escaped[i + 1:i + 4], 10) for i in range(0, len(escaped), 4))
            except ValueError as error:
                raise TableDataError("Unicode literal byte overflow") from error
            if not 1 <= len(chunk) <= 4096 or (continuation and len(chunk) != 4096):
                raise TableDataError("Unicode literal chunk size mismatch")
            chunks.append(chunk)
            position = match.end()
            if not continuation:
                break
        packed[name] = b"".join(chunks)
        if len(packed[name]) != size:
            raise TableDataError("Unicode packed inventory mismatch")
    trailer = source[position:]
    if not trailer.startswith(b"local function uint(s, p, n)\n") or not trailer.endswith(
        (f'return {{identity = "{DATA_IDENTITY}", max_decomposition = 4,\n'
         '        get = get, compose = compose, props = props, decomp = decomp}\n').encode("ascii")
    ):
        raise TableDataError("Unicode authenticated trailer mismatch")
    return MappingProxyType(packed)


class Properties(NamedTuple):
    idna: int
    bidi: int
    ccc: int  # pinned Go compressed leading CCC (order/equality preserving)
    nfc_flags: int
    leading: int
    decomposition: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class UnicodeTables:
    starts: tuple[int, ...]
    indices: tuple[int, ...]
    properties: tuple[Properties, ...]
    compositions: MappingProxyType
    packed: MappingProxyType

    def lookup(self, scalar: int) -> Properties:
        if type(scalar) is not int or not 0 <= scalar <= 0x10FFFF:
            raise ValueError("not a Unicode code point")
        return self.properties[self.indices[bisect_right(self.starts, scalar) - 1]]

    def compose(self, first: int, second: int) -> int:
        # Preserve x/text's lookup key, including supplementary-plane aliases.
        return self.compositions.get(((first & 0xFFFF) << 16) | (second & 0xFFFF), 0)

    def verify_exhaustive_inventory(self) -> str:
        """Reconstruct the previously proved raw Go property stream, no Go run.

        Iterates each code point with the Python lookup and independently checks
        the uncompressed SHA-256, including decompositions and composition pairs.
        The hash is pinned in Python code, not taken on trust from a manifest.
        """
        digest = hashlib.sha256()
        for scalar in range(0x110000):
            p = self.lookup(scalar)
            digest.update(bytes((p.idna, p.bidi, p.ccc, p.nfc_flags, p.leading, len(p.decomposition))))
            for part in p.decomposition:
                digest.update(struct.pack(">I", part))
        digest.update(struct.pack(">I", len(self.compositions) * 8))
        # The Lua packing sorts by pair key. Upstream norm/maketables.go emits
        # recompMapPacked in ascending composed-rune order (the chars slice).
        for key, value in sorted(self.compositions.items(), key=lambda pair: pair[1]):
            digest.update(struct.pack(">II", key, value))
        result = digest.hexdigest()
        if result != GO_PROPERTY_ORACLE_SHA256:
            raise TableDataError("exhaustive Unicode oracle hash mismatch")
        return result


def tables_from_source(source: bytes) -> UnicodeTables:
    packed = parse_pinned_literals(source)
    ranges, props, decomps, pairs = (packed[k] for k in ("ranges", "props", "decomp", "compositions"))
    starts = tuple(_uint(ranges, i, 3) for i in range(0, len(ranges), 5))
    indices = tuple(_uint(ranges, i + 3, 2) for i in range(0, len(ranges), 5))
    if starts[0] != 0 or starts[-1] > 0x10FFFF or any(a >= b for a, b in zip(starts, starts[1:])):
        raise TableDataError("Unicode ranges are not a complete ordered partition")
    if set(indices) != set(range(2099)):
        raise TableDataError("Unicode property reference inventory mismatch")
    properties = []
    for i in range(0, len(props), 9):
        flags, bidi, ccc, nfc, leading = props[i:i + 5]
        offset, count = _uint(props, i + 5, 3), props[i + 8]
        if flags >> 3 > 4 or bidi > 24 or ccc >= 56 or nfc >= 64 or leading > 3:
            raise TableDataError("Unicode property out of range")
        if offset % 3 or count > 4 or offset + count * 3 > len(decomps):
            raise TableDataError("Unicode decomposition bounds mismatch")
        decomposition = tuple(_uint(decomps, j, 3) for j in range(offset, offset + count * 3, 3))
        if any(cp > 0x10FFFF or 0xD800 <= cp <= 0xDFFF for cp in decomposition):
            raise TableDataError("Unicode decomposition scalar mismatch")
        properties.append(Properties(flags, bidi, ccc, nfc, leading, decomposition))
    compositions = {}
    previous = -1
    for i in range(0, len(pairs), 7):
        key, value = _uint(pairs, i, 4), _uint(pairs, i + 4, 3)
        if key <= previous or not 0 < value <= 0x10FFFF or 0xD800 <= value <= 0xDFFF:
            raise TableDataError("Unicode composition inventory mismatch")
        compositions[key], previous = value, key
    if len(set(compositions.values())) != 941:
        raise TableDataError("Unicode composition result inventory mismatch")
    for cp in range(128):
        if indices[bisect_right(starts, cp) - 1] != _uint(packed["ascii"], cp * 2, 2):
            raise TableDataError("Unicode ASCII lookup mismatch")
    return UnicodeTables(starts, indices, tuple(properties), MappingProxyType(compositions), packed)


def _load_tables() -> UnicodeTables:
    try:
        with DATA_PATH.open("rb") as source:
            return tables_from_source(source.read(DATA_SOURCE_BYTES + 1))
    except OSError as error:
        raise TableDataError("pinned Unicode data unavailable") from error


# Eager authentication: an ASCII-only fixture run must not mask missing data.
TABLES = _load_tables()


def _adapt(delta: int, points: int, first: bool) -> int:
    delta //= 700 if first else 2
    delta += delta // points
    bias = 0
    while delta > 455:
        delta //= 35
        bias += 36
    return bias + 36 * delta // (delta + 38)


def decode_punycode(payload: str) -> tuple[int, ...]:
    """Bounded RFC3492 decoder with the pinned Go signed-int32 rejection limit."""
    if not 1 <= len(payload) <= 59 or re.fullmatch("[a-z0-9-]+", payload) is None:
        raise URLValidationError()
    split = payload.rfind("-")
    if split == 0 or split == len(payload) - 1:
        raise URLValidationError()  # empty/ASCII-only labels cannot be valid A-labels
    result = list(map(ord, payload[:split])) if split >= 0 else []
    position, insertion, scalar, bias = split + 1, 0, 128, 72
    while position < len(payload):
        old, weight, k = insertion, 1, 36
        while True:
            if position == len(payload):
                raise URLValidationError()
            char = payload[position]
            if "a" <= char <= "z":
                digit = ord(char) - ord("a")
            elif "0" <= char <= "9":
                digit = ord(char) - ord("0") + 26
            else:
                raise URLValidationError()
            position += 1
            if digit * weight > 0x7FFFFFFF - insertion:
                raise URLValidationError()
            insertion += digit * weight
            threshold = max(1, min(26, k - bias))
            if digit < threshold:
                break
            weight *= 36 - threshold
            if weight > 0x7FFFFFFF:
                raise URLValidationError()
            k += 36
        count = len(result) + 1
        if count > 59:
            raise URLValidationError()
        bias = _adapt(insertion - old, count, old == 0)
        scalar += insertion // count
        insertion %= count
        if scalar > 0x10FFFF or 0xD800 <= scalar <= 0xDFFF:
            raise URLValidationError()
        result.insert(insertion, scalar)
        insertion += 1
    return tuple(result)


class _Rune(NamedTuple):
    scalar: int
    ccc: int
    flags: int
    leading: int = 0
    decomposition: tuple[int, ...] = ()


def _rune(scalar: int) -> _Rune:
    p = TABLES.lookup(scalar)
    return _Rune(scalar, p.ccc, p.nfc_flags, p.leading, p.decomposition)


def _quick_span(runes: list[_Rune], start: int) -> int:
    index, segment, last_class, nonstarters = start, start, 0, 0
    while index < len(runes):
        current = runes[index]
        if current.scalar < 128:
            # Go's ASCII fast path records the LAST ASCII starter in the run.
            while index < len(runes) and runes[index].scalar < 128:
                index += 1
            segment, last_class, nonstarters = index - 1, 0, 0
            continue
        nonstarters += current.leading
        if nonstarters > 30:
            return segment
        if current.leading == 0:
            segment, nonstarters = index, current.flags & 3
        elif last_class > current.ccc:
            return segment
        if current.flags & 16:
            return segment
        last_class = current.ccc
        index += 1
    return index


def _compose_segment(segment: list[_Rune]) -> list[_Rune]:
    if not segment:
        return []
    result, starter, hangul = [segment[0]], 0, False
    for current in segment[1:]:
        # x/text enters Hangul mode for the rest of this segment, not just one
        # candidate. A composed rune's properties are deliberately cleared.
        hangul |= 0x1100 <= current.scalar <= 0x11FF
        combined = 0
        if hangul or current.flags & 8:
            previous_class = result[-1].ccc
            if previous_class == 0:
                starter = len(result) - 1
            blocked = starter != len(result) - 1 and previous_class >= current.ccc
            if not blocked:
                first, second = result[starter].scalar, current.scalar
                if not hangul:
                    combined = TABLES.compose(first, second)
                elif 0x1100 <= first < 0x1113 and 0x1161 <= second < 0x1176:
                    combined = 0xAC00 + (first - 0x1100) * 588 + (second - 0x1161) * 28
                elif 0xAC00 <= first < 0xD7A4 and (first - 0xAC00) % 28 == 0 and 0x11A7 < second < 0x11C3:
                    combined = first + second - 0x11A7
        if combined:
            result[starter] = _Rune(combined, 0, 0)
        else:
            result.append(current)
    return result


def nfc_normal(text: str) -> bool:
    """Pinned Go NFC/stream-safe fixed-point test, bounded to A-label scalars."""
    if type(text) is not str or len(text) > 59 or any(0xD800 <= ord(c) <= 0xDFFF for c in text):
        return False
    runes = [_rune(ord(char)) for char in text]
    cursor = _quick_span(runes, 0)
    if cursor == len(runes):
        return True
    nonstarters = 0
    buffer: list[_Rune] = []
    comparison = cursor

    def flush() -> bool:
        nonlocal comparison
        for part in _compose_segment(buffer):
            if comparison >= len(runes) or part.scalar != runes[comparison].scalar:
                return False
            comparison += 1
        buffer.clear()
        return True

    def ordered(part: _Rune) -> bool:
        if len(buffer) == 32:
            return False
        position = len(buffer)
        if part.ccc:
            while position and buffer[position - 1].ccc > part.ccc:
                position -= 1
        buffer.insert(position, part)
        return True

    def insert(current: _Rune) -> bool:
        if 0xAC00 <= current.scalar < 0xD7A4:
            offset = current.scalar - 0xAC00
            buffer.extend((_Rune(0x1100 + offset // 588, 0, 0), _Rune(0x1161 + offset // 28 % 21, 0, 0)))
            if offset % 28:
                buffer.append(_Rune(0x11A7 + offset % 28, 0, 0))
            return len(buffer) <= 32
        if not current.flags & 4:
            return ordered(current)
        for scalar in current.decomposition:
            part = _rune(scalar)
            if part.ccc == 0 and not part.flags & 8 and buffer and not flush():
                return False
            if not ordered(part):
                return False
        return True

    def stream(current: _Rune) -> int:
        nonlocal nonstarters
        nonstarters += current.leading
        if nonstarters > 30:
            nonstarters = 0
            return 2
        if current.leading == 0:
            nonstarters = current.flags & 3
            return 1
        return 0

    while cursor < len(runes):
        comparison = cursor
        if stream(runes[cursor]) == 2:
            if not ordered(_Rune(0x034F, 0, 0)):
                return False
        else:
            if not insert(runes[cursor]):
                return False
            cursor += 1
            while cursor < len(runes):
                state = stream(runes[cursor])
                if state == 1:
                    break
                if state == 2:
                    if not ordered(_Rune(0x034F, 0, 0)):
                        return False
                    break
                if not insert(runes[cursor]):
                    return False
                cursor += 1
        if not flush():
            return False
        cursor = _quick_span(runes, cursor)
    return True


# Exact zero-based Go ContextJ state table, including default-to-start entries.
_JOIN = (
    (0, 2, 2, 0, 0, 5, 5, 1), (0, 2, 2, 0, 0, 0, 0, 0),
    (0, 2, 2, 2, 0, 5, 4, 3), (0, 2, 2, 2, 0, 0, 0, 0),
    (0, 5, 2, 4, 0, 5, 5, 4), (5, 5, 5, 5, 5, 5, 5, 5),
)
_DNS_LABEL = re.compile(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?")


def valid_alabel(label: str) -> bool:
    if type(label) is not str or not label.startswith("xn--") or _DNS_LABEL.fullmatch(label) is None:
        return False
    try:
        scalars = decode_punycode(label[4:])
    except URLValidationError:
        return False
    if not scalars or all(cp < 128 for cp in scalars):
        return False
    properties = [TABLES.lookup(cp) for cp in scalars]
    if any(not p.idna & 1 for p in properties):
        return False
    decoded = "".join(map(chr, scalars))
    if not nfc_normal(decoded):
        return False
    raw = decoded.encode("utf-8")
    if (len(raw) > 4 and raw[2:4] == b"--") or raw.startswith(b"-") or raw.endswith(b"-"):
        return False
    if properties[0].idna & 2:
        return False
    if 0x200C in scalars or 0x200D in scalars:
        state = 0
        for scalar, p in zip(scalars, properties):
            joining = 5 if scalar == 0x200D else 6 if scalar == 0x200C else p.idna >> 3
            state = _JOIN[state][joining]
            if p.idna & 4:
                state = _JOIN[state][7]
        if state in (4, 5):
            return False
    classes = [p.bidi for p in properties]
    if any(c in (1, 5, 13) for c in classes):  # R / AN / AL
        if classes[0] not in (1, 13) or any(c not in (1, 2, 3, 4, 5, 6, 10, 11, 12, 13) for c in classes):
            return False
        final = next((c for c in reversed(classes) if c != 12), None)
        if final not in (1, 2, 5, 13) or (2 in classes and 5 in classes):
            return False
    # The stdlib's pure RFC3492 encoder uses no Unicode database. Its independent
    # algorithm cannot overflow Go's int32 bound for <=59 validated scalars.
    return decoded.encode("punycode").decode("ascii") == label[4:]


def _ipv4(host: str) -> bool:
    parts = host.split(".")
    return len(parts) == 4 and all(
        re.fullmatch(r"0|[1-9][0-9]{0,2}", part) and int(part) <= 255 for part in parts
    )


def _ipv6(host: str) -> bool:
    # Syntax only: neither Python ipaddress nor normalization of presentation.
    if "." in host:
        prefix, colon, dotted = host.rpartition(":")
        if not colon or not _ipv4(dotted):
            return False
        host = prefix + ":0:0"
    if host.count("::") > 1:
        return False
    if "::" in host:
        first, last = host.split("::")
        parts = (first.split(":") if first else []) + (last.split(":") if last else [])
        length_ok = len(parts) < 8
    else:
        parts = host.split(":")
        length_ok = len(parts) == 8
    return length_ok and all(re.fullmatch(r"[0-9a-f]{1,4}", part) for part in parts)


@dataclass(frozen=True, slots=True)
class CanonicalURL:
    canonical_url: str
    scheme: str
    host: str
    port: int
    explicit_port: bool
    is_ip: bool

    @property
    def url_id(self) -> str:
        return hashlib.sha256(b"mifolyo-url:v1\0" + self.canonical_url.encode("ascii")).hexdigest()

    @property
    def origin(self) -> str | None:
        return None if self.is_ip else f"{self.scheme}://{self.host}:{self.port}"


_PATH = frozenset("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/:@!$&'()*+,;=-._~")
_QUERY = _PATH | {"?"}


def _component(component: str, safe: frozenset[str]) -> None:
    position = 0
    while position < len(component):
        if component[position] == "%":
            pair = component[position + 1:position + 3]
            if re.fullmatch("[0-9A-F]{2}", pair) is None:
                raise URLValidationError()
            value = int(pair, 16)
            if value < 0x20 or value == 0x7F:
                raise URLValidationError()
            if value == 0xC2 and re.match(r"%[89][0-9A-F]", component[position + 3:]):
                raise URLValidationError()
            position += 3
        else:
            if component[position] not in safe:
                raise URLValidationError()
            position += 1


def validate_identity(value: object) -> CanonicalURL:
    """Accept only Go CanonicalizeURLV1 fixed points, including IP identities.

    Error precedence is deterministic (type/UTF-8, length, raw envelope,
    fragment, syntax/authority, port, components); error *categories* preserve
    the existing verifier fixtures. Go's accepted set, not its internal parse
    error text, is authoritative. No implicit user-input normalization occurs.
    """
    if type(value) is not str:
        raise URLValidationError("FIXTURE_TYPE")
    try:
        raw = value.encode("utf-8", "strict")
    except UnicodeEncodeError as error:
        raise URLValidationError("INVALID_UTF8") from error
    if len(raw) > 2048:
        raise URLValidationError("URL_TOO_LONG")
    if not raw or any(b < 33 or b > 126 or b == 92 for b in raw):
        raise URLValidationError()
    if "#" in value:
        raise URLValidationError("URL_FRAGMENT_FORBIDDEN")
    if value.startswith("http://"):
        scheme, rest, default = "http", value[7:], 80
    elif value.startswith("https://"):
        scheme, rest, default = "https", value[8:], 443
    else:
        raise URLValidationError()
    authority, slash, tail = rest.partition("/")
    if not authority or not slash or "?" in authority:
        raise URLValidationError()
    if "@" in authority:
        raise URLValidationError("URL_USERINFO_FORBIDDEN")
    explicit, port_text = False, ""
    if authority.startswith("["):
        host, close, suffix = authority[1:].partition("]")
        if not close or not _ipv6(host):
            raise URLValidationError()
        if suffix:
            if not suffix.startswith(":"):
                raise URLValidationError()
            explicit, port_text = True, suffix[1:]
        is_ip = True
    else:
        if authority.count(":") > 1:
            raise URLValidationError()
        host, colon, port_text = authority.partition(":")
        explicit = bool(colon)
        labels = host.split(".")
        if len(host) > 253 or any(_DNS_LABEL.fullmatch(label) is None for label in labels):
            raise URLValidationError()
        is_ip = len(labels) == 4 and all(re.fullmatch("[0-9]+", part) for part in labels)
        if is_ip and not _ipv4(host):
            raise URLValidationError()
        if any(label.startswith("xn--") and not valid_alabel(label) for label in labels):
            raise URLValidationError()
    port = default
    if explicit:
        if re.fullmatch("[1-9][0-9]{0,4}", port_text) is None or int(port_text) > 65535:
            raise URLValidationError()
        port = int(port_text)
        if port == default:
            raise URLValidationError("URL_DEFAULT_PORT_FORBIDDEN")
    path, question, query = ("/" + tail).partition("?")
    _component(path, _PATH)
    if question:
        _component(query, _QUERY)
    return CanonicalURL(value, scheme, host, port, explicit, is_ip)


def derive_origin(value: object) -> str:
    """Go DeriveCanonicalOrigin semantics, NOT general identity or static admission."""
    result = validate_identity(value)
    if result.is_ip:
        raise URLValidationError("URL_IP_LITERAL_FORBIDDEN")
    assert result.origin is not None
    return result.origin
